### ISSUE TITLE
GithubActions的问题

### ISSUE THREAD

**Issue by niuhuan** [niuhuan/pikapika#111]
我在尝试用GithubActions自动构建，遇到了诸多问题，@zhongFly

**Comment by niuhuan** [comment]
我只希望在windows中安装msys2以便运行cgo。

我在 yaml 中设置了  ${{ matrix.config.target }} == "windows"，但是在ubuntu中仍然会被执行。
我更希望用if去判断流程，而不是针对每个平台都写一个构建脚本，因为重复的步骤比较多。

```yaml
- if: ${{ steps.check_asset.outputs.* }} == "BUILD" && ${{ matrix.config.target }} == "windows"
  name: Setup msys2
  uses: msys2/setup-msys2@v2
  with:
    install: gcc make
```
